version: '2.1'
orbs:
  slack: circleci/slack@4.1
  jq: circleci/jq@2.2.0
jobs:
  talisman:
    docker:
      - image: rameinstein/talisman:talisman
        auth:
          username: rameinstein  # can specify string literal values
          password: ygvBHU@3690
    environment:
      TALISMAN_HOME: /root/.talisman/bin
      TALISMAN_INTERACTIVE: false
    steps:
      - checkout
      - jq/install
      - run:
          name: Check Talisman
          command: $TALISMAN_HOME/talisman_linux_amd64 --scan || echo "done" # I've added --ignoreHistory to the end here 
      - store_artifacts:
          path: talisman_report/talisman_reports/data
          destination: talisman_report
      - run:
          name: Get artifacts
          command: |
            export URL_API_TEST_RESULTS=$(curl -X GET "https://circleci.com/api/v2/project/github/ramkumareinstein/leaky-repo/$CIRCLE_BUILD_NUM/artifacts" \
            -H "Accept: application/json" \
            -u "$CIRCLE_API_TOKEN:") | jq ".items[].url"
            echo "echo API Tests are located at: $URL_API_TEST_RESULTS"
            
      - slack/notify:
                custom: |
                  {
                    "blocks": [
                      {
                         "type": "section",
                          "text": {
                          "type": "mrkdwn",
                          "text": "Current Job : $CIRCLE_JOB"
                      }
                    },
                      {
                        "type": "section",
                        "fields": [
                          {
                            "type": "plain_text",
                            "text": "Talisman Scan completed ",
                            "emoji": true
                          }
                        ]
                      },
                      {
                        "type": "actions",
                        "elements": [
                          {
                              "type": "button",
                              "text": {
                                            "type": "plain_text",
                                            "text": "View API Test Results"
                                          },
                              "url": "${URL_API_TEST_RESULTS}"
                          }
                          ]
                      }
                    ]
                  }
                event: always
           
workflows:
  send-notification:
    jobs:
      - talisman
