version: '2.1'
orbs:
  slack: circleci/slack@4.1
jobs:
  deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run: echo "deploy my app"
      - slack/notify:
          event: fail
          mentions: '@EngineeringTeam'
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
  test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run: echo "test my app"
  talisman:
    docker:
      - image: rameinstein/talisman:talisman
    resource_class: small
    environment:
      TALISMAN_HOME: /root/.talisman/bin
      TALISMAN_INTERACTIVE: false
    steps:
      - checkout
      - run:
          name: Check Talisman
          command: $TALISMAN_HOME/talisman_linux_amd64 --scan || echo "done" # I've added --ignoreHistory to the end here
      - slack/notify:
                custom: |
                  {
                    "blocks": [
                      {
                        "type": "section",
                        "fields": [
                          {
                            "type": "plain_text",
                            "text": "*This is a text notification*",
                            "emoji": true
                          }
                        ]
                      }
                    ]
                  }
                event: always
      - store_artifacts:
          path: talisman_report/talisman_reports/data
          destination: talisman_report
workflows:
  test-and-deploy:
    jobs:
      - test
      - slack/on-hold:
          context: slack_secrets
          filters:
            tags:
              only: /^v.*/
          requires:
            - test
      - pause_workflow:
          filters:
            tags:
              only: /^v.*/
          requires:
            - test
            - slack/on-hold
          type: approval
      - deploy:
          filters:
            tags:
              only: /^v.*/
          requires:
            - pause_workflow
      - talisman
