version: '2.1'
orbs:
  slack: circleci/slack@4.1
jobs:
  talisman:
    docker:
      - image: rameinstein/talisman:talisman
        auth:
          username: rameinstein  # can specify string literal values
          password: ygvBHU@3690
    environment:
      TALISMAN_HOME: /root/.talisman/bin
      TALISMAN_INTERACTIVE: false
    steps:
      - checkout
      - run:
          name: Check Talisman
          command: $TALISMAN_HOME/talisman_linux_amd64 --scan || echo "done" # I've added --ignoreHistory to the end here 
      - store_artifacts:
          path: talisman_report/talisman_reports/data
          destination: talisman_report
      - run:
          name: Get artifacts
          when: on_success
          command: |
            artifacts=$(curl -X GET "https://circleci.com/api/v2/project/github/ramkumareinstein/leaky-repo/$CIRCLE_BUILD_NUM/artifacts" \
            -H "Accept: application/json" \
            -u "$CIRCLE_API_TOKEN:")
            # generate a heredoc in BASH_ENV
            # the '\<<' is a CircleCI escape
            echo "read -r -d '' STORED_ARTIFACTS \<< 'EOF_ARTIFACTS'" >> $BASH_ENV
            echo "$artifacts" >> $BASH_ENV
            echo "EOF_ARTIFACTS" >> $BASH_ENV  
      - slack/notify:
                custom: |
                  {
                    "blocks": [
                      {
                         "type": "section",
                          "text": {
                          "type": "mrkdwn",
                          "text": "Current Job : $CIRCLE_JOB"
                      }
                    },
                      {
                        "type": "section",
                        "fields": [
                          {
                            "type": "plain_text",
                            "text": "Talisman Scan completed ",
                            "emoji": true
                          }
                        ]
                      },
                      {
                        "type": "actions",
                        "elements": [
                          {
                            "type": "button",
                            "action_id": "success_tagged_deploy_view",
                            "text": {
                              "type": "plain_text",
                              "text": "View Artifact"
                            },
                            "url": "${CIRCLE_BUILD_URL}"
                          }
                          ]
                      }
                    ]
                  }
                event: always
           
workflows:
  send-notification:
    jobs:
      - talisman
